/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_PoseEstimator */

#ifndef _Included_com_seeta_sdk_PoseEstimator
#define _Included_com_seeta_sdk_PoseEstimator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_PoseEstimator
 * Method:    construct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_track_seeta6_PoseEstimator_construct
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_PoseEstimator
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
 /*
JNIEXPORT void JNICALL Java_com_example_track_seeta6_PoseEstimator_construct1
  (JNIEnv *, jobject, jstring, jstring, jint);
*/
/*
 * Class:     com_seeta_sdk_PoseEstimator
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_track_seeta6_PoseEstimator_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_PoseEstimator
 * Method:    Estimate
 * Signature: (Lcom/seeta/sdk/SeetaImageData;Lcom/seeta/sdk/SeetaRect;[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_example_track_seeta6_PoseEstimator_Estimate
  (JNIEnv *, jobject, jobject, jobject, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
